### ISSUE TITLE
Undefined index: glpi_plugin_ticketmail_profile

### ISSUE THREAD

**Issue by tackephap** [Probesys/glpi-plugins-ticketmail#1]
I got HTTP ERROR 500 when click "SEND" button while loading /plugins/ticketmail/front/ticketmail.form.php.

Also got this error on php-errors.log:
2016-06-29 16:17:28 [26@host]
  **\* PHP Notice(8): Undefined index: glpi_plugin_ticketmail_profile
  Backtrace :
  plugins/ticketmail/inc/profile.class.php:233  
  plugins/ticketmail/inc/profile.class.php:99        plugin_ticketmail_haveRight()
  inc/commonglpi.class.php:208                       PluginTicketmailProfile->getTabNameForItem()
  inc/commonglpi.class.php:166                       CommonGLPI->addStandardTab()
  ajax/updatecurrenttab.php:50                       CommonGLPI->defineAllTabs()

Can you help ?

[CONFIG]
GLPI 0.90.3
Ticket mail: 3.1.0
Operating system: Linux 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39 UTC 2016 x86_64
PHP 5.4.45 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
    date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash,
    mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, session, shmop, sockets, sqlite3, standard, sysvmsg,
    sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
    upload_max_filesize="2M" 
Software: Apache/2.2.15 (CentOS) (Apache/2.2.15 (CentOS) Server )
    Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Server Software: MySQL Community Server (GPL) by Remi
    Server Version: 5.5.48
    Server SQL Mode: 
    Parameters: glpi@localhost/glpi
    Host info: Localhost via UNIX socket
htmLawed version 1.1.21 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/html/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/html/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/html/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/var/www/html/glpi/lib/Zend)
SimplePie version 1.3.1 in (/var/www/html/glpi/lib/simplepie)
TCPDF version 6.2.12 in (/var/www/html/glpi/lib/tcpdf)
ircmaxell/password-compat in (/var/www/html/glpi/lib/password_compat). Compatitility: Ok
List Plug-in
    behaviors            Name: Behaviours                     Version: 1.0        State: Enabled
    dashboard            Name: Dashboard                      Version: 0.7.3      State: Enabled
    environment          Name: Environment                    Version: 1.9.0      State: Enabled
    fusioninventory      Name: FusionInventory                Version: 0.90+1.3   State: Enabled
    order                Name: Orders management              Version: 0.85+1.2   State: Enabled
    additionalalerts     Name: Others alerts                  Version: 1.8.0      State: Enabled
    ticketmail           Name: Ticket Mail                    Version: 3.1.0      State: Enabled

**Comment by philgprobesys** [comment]
hi,

i have make a modification to the plugin_ticketmail_haveRight method.
I hope this solve your problem.



Le 29/06/2016 à 11:55, lolodup a écrit :
>
> I got HTTP ERROR 500 when click "SEND" button while loading 
> /plugins/ticketmail/front/ticketmail.form.php.
>
> Also got this error on php-errors.log:
> 2016-06-29 16:17:28 [26@host]
> *** PHP Notice(8): Undefined index: glpi_plugin_ticketmail_profile
> Backtrace :
> plugins/ticketmail/inc/profile.class.php:233
>
> plugins/ticketmail/inc/profile.class.php:99 plugin_ticketmail_haveRight()
> inc/commonglpi.class.php:208 PluginTicketmailProfile->getTabNameForItem()
> inc/commonglpi.class.php:166 CommonGLPI->addStandardTab()
> ajax/updatecurrenttab.php:50 CommonGLPI->defineAllTabs()
>
> Can you help ?
>
> [CONFIG]
> GLPI 0.90.3
> Ticket mail: 3.1.0
> Operating system: Linux 2.6.32-573.22.1.el6.x86_64 #1 
> <https://github.com/Probesys/glpi-plugins-ticketmail/issues/1> SMP Wed 
> Mar 23 03:35:39 UTC 2016 x86_64
> PHP 5.4.45 apache2handler (Core, PDO, Phar, Reflection, SPL, 
> SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
> date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, 
> iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash,
> mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, 
> session, shmop, sockets, sqlite3, standard, sysvmsg,
> sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlwriter, 
> xsl, zip, zlib)
> Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" 
> safe_mode="" session.save_handler="files"
> upload_max_filesize="2M"
> Software: Apache/2.2.15 (CentOS) (Apache/2.2.15 (CentOS) Server )
> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) 
> Chrome/51.0.2704.103 Safari/537.36
> Server Software: MySQL Community Server (GPL) by Remi
> Server Version: 5.5.48
> Server SQL Mode:
> Parameters: glpi@localhost/glpi
> Host info: Localhost via UNIX socket
> htmLawed version 1.1.21 in (/var/www/html/glpi/lib/htmlawed)
> phpCas version 1.3.4 in (/var/www/html/glpi/lib/phpcas)
> PHPMailer version 5.2.8 in (/var/www/html/glpi/lib/phpmailer)
> ZetaComponent ezcGraph installed in (/var/www/html/glpi/lib/zeta/Base): OK
> Zend Framework version 2.4.9 in (/var/www/html/glpi/lib/Zend)
> SimplePie version 1.3.1 in (/var/www/html/glpi/lib/simplepie)
> TCPDF version 6.2.12 in (/var/www/html/glpi/lib/tcpdf)
> ircmaxell/password-compat in (/var/www/html/glpi/lib/password_compat). 
> Compatitility: Ok
> List Plug-in
> behaviors Name: Behaviours Version: 1.0 State: Enabled
> dashboard Name: Dashboard Version: 0.7.3 State: Enabled
> environment Name: Environment Version: 1.9.0 State: Enabled
> fusioninventory Name: FusionInventory Version: 0.90+1.3 State: Enabled
> order Name: Orders management Version: 0.85+1.2 State: Enabled
> additionalalerts Name: Others alerts Version: 1.8.0 State: Enabled
> ticketmail Name: Ticket Mail Version: 3.1.0 State: Enabled
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Probesys/glpi-plugins-ticketmail/issues/1>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/ABNP_dF_K_XpoyGXpB9y0dDfFKtTbMdoks5qQkD6gaJpZM4JA9i4>.
>


-- 
philippe GODOT

probeSys
9 rue de chamrousse
38000 GRENOBLE
Tél : 09 74 76 47 86
Fax : 09 74 76 33 31
site web : http://www.probesys.com

**Comment by lolodup** [comment]
Hi,
Thanks, i can now see the tab on my profile, 
![chrome_2016-06-30_10-01-38](https://cloud.githubusercontent.com/assets/20203870/16475578/db6f79e8-3ea9-11e6-8669-40e2245ca55c.png)
but i'm unable to save the setting after switch  "tab display" from "No" to "Yes" then click on "Update" button it's display the follwoing message...
![chrome_2016-06-30_10-01-51](https://cloud.githubusercontent.com/assets/20203870/16475577/db6ab67e-3ea9-11e6-88d7-53cad9bb3667.png)

**Comment by philgprobesys** [comment]
hi,
i have install a new glpi 0.90.3 instance with empty databases.
I haven't problem to manage plugin permissions in profile with the glpi user.
i have push a new commit to replace the array_key_exists by on e isset but i don't think it's change anything.
can you activate the debug mode in glpi and show if you have a 'glpi_plugin_ticketmail_profile' entry in your session ?

**Comment by lolodup** [comment]
I updated update the file profile.class.php, set log debug level on GLPI, restart httpd, but still not working and no trace of glpi_plugin_ticketmail_profile on any php logs file.

**Comment by philgprobesys** [comment]
This issue is very old and the plugin version is now 3.4.0
I close the issue, if the problem persit with the last version re-open it.
