### ISSUE TITLE
Glpi 10 support

### ISSUE THREAD

**Issue by FabFara** [Probesys/glpi-plugins-ticketmail#12]
Please, upgrade the plugin to support GLPI 10

**Comment by philgprobesys** [comment]
Hi, we have planned to migrate all of our GLPI plugin at the begin of 2023.

**Comment by ctresvaux** [comment]
A new release for Glpi10 compatibilty has been publihed.
Can you please test it ?
Thank you

**Comment by boisrobe** [comment]
just a question, i find your plugin in https://plugins.glpi-project.org/ but not in the market place of glpi. 
Is it normal ?

**Comment by FabFara** [comment]
> A new release for Glpi10 compatibilty has been publihed. Can you please test it ? Thank you

It's works! Thanks!
