### ISSUE TITLE
First of all, this plugin is really good.

### ISSUE THREAD

**Issue by ts2050** [Probesys/glpi-plugins-ticketmail#13]
Would it be possible for these emails to be follow-ups on the ticket? Once sent, only the record that was sent remains in the history, but this message cannot be consulted in the ticket history.

**Comment by cornebrouwers** [comment]
Same here, it would be very helpful to see the message itself in Tab 'Tickets' (conversation history) of the ticket.
Also, it would be helpful to automatically add the ticket ID to the subject-line (example '[GLPI #0000713]) ', so we can see replies automatically in the conversation history as well. Without it, a reply creates a new ticket.

Thanks in advance

**Comment by philgprobesys** [comment]
I @cornebrouwers and @Thrbnsnk ,
We have change the method to add ticket info on the subject of the message to insert info like '[GLPI #0000713]
we add also add the message id on the MessageID header.
Unfortunetly, the size of the history field is not enough big to insert all the body of the mail, only the start of the body can be add. I've change the code, you can update the plugin with the V.3.6.3 release
