### ISSUE TITLE
Ticket-Mail not added as "answer" or "note" in ticket itself

### ISSUE THREAD

**Issue by usterei** [Probesys/glpi-plugins-ticketmail#15]
After sending an email out of the ticket using the plugin, the ticket should be integrated in information flow within ticket history.
The mail is being sent perfectly with version 3.9.3, but its also "lost" - meaning not in the ticket for the other users to be seen.

**Comment by usterei** [comment]
in version 3.6.5 after sending the email now a task is created saying that a mail is sent. It would be extremely useful if the email sent would be content of the task, as other helpdesk agents may not know what the email was saying.

**Comment by philg38** [comment]
Hi @usterei ,
it's possible to change the code of the plugin to add all the mail content into the Task but i was afraid the the content of this task will be too long. I reopen this issue to change the code on next version of the plugin

**Comment by philg38** [comment]
After reflexion, i think that the best solution is to add the content of the mail on a Document ( txt or eml for example ) associate to the task
