### ISSUE TITLE
Envoie données du ticket impossible

### ISSUE THREAD

**Issue by seboulonnais** [Probesys/glpi-plugins-ticketmail#4]
Je ne suis en mesure que d'envoyer la demande initiale du ticket et non pas tout son suivi. Cela perd de son intérêt. J'ai cherché comment changer cela sans succès.

**Comment by philgprobesys** [comment]
bonjour,
en effet cela n'est actuellement pas possible mais pourrait être ajouté dans une future version

**Comment by seboulonnais** [comment]
Ok dans ce cas le descriptif me semble erroné. "Ce plugin permet d'envoyer les informations de suivi et tâches d'un ticket " Il permet juste d'envoyer la demande initiale, pas le suivi ni les tâches.
