### ISSUE TITLE
Cant send e-mail

### ISSUE THREAD

**Issue by danielloiola** [Probesys/glpi-plugins-ticketmail#7]
**Error at mail.log when we try to send e-mail:**

Error during send email form ticketMail plugin:
 ** RECIPIANT: alessandra.leal@ticway.com.br
 ** SUBJECT: 21312312
 ** BODY: <h3>Content of the initial ticket</h3>
<p>04-06-2021 18:15</p>
<div>
<h1>Dados do formulário</h1>
<h2>Dados de Contato</h2>
<div><strong>1) Informe o Telefone de Contato : </strong>321312312</div>
<div><strong>2) Qual sua disponíbilidade : </strong>Tarde</div>
<h2>Dados da Solicitação</h2>
<div><strong>3) Selecione o serviço : </strong>Hardware > Notebook > Impressora > Falha/Erro</div>
<div><strong>4) Título do chamado : </strong>21312312</div>
<div><strong>5) Descreva sua solicitação : </strong>
<p>12312321</p>
</div>
</div>
<h3>Ticket tasks and followups associate to the ticket</h3>
 ** ERROR: SMTP Error: data not accepted.SMTP server error: DATA END command failed Detail: 5.2.252 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExce                             ptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:03003A12, 1.36674:01000000, 1.61250:000000                             00, 1.45378:02000000, 1.44866:00000000, 1.36674:7A000000, 1.61250:00000000, 1.45378:05000000, 1.44866:00140000, 1.36674:0A000000, 1.61250:00000000, 1.45378:1600                             0000, 1.44866:56240000, 1.36674:0E000000, 1.61250:00000000, 1.45378:6F240000, 1.44866:20020000, 16.55847:89130000, 17.4 SMTP code: 5542021-06-04 19:47:23 **[13@csc.ticway.com.br]**

<p></p>
<p></p>
<p></p>
**The plugin is sending e-mail using **13@csc.ticway.com.br**, this account not exist, the plugin needs to use the default e-mail account configured in GLPI, do you know how to fix?**

**Comment by benshoes** [comment]
+1
