### ISSUE TITLE
Hide Private Task

### ISSUE THREAD

**Issue by BboivinFOCSS** [Probesys/glpi-plugins-ticketmail#8]
Hi Dev'

Is it possible to configure if you want (or not) to hide private task in the default mail ?

**Comment by philgprobesys** [comment]
Hi @BboivinFOCSS !
It's a good idea, i add the issue on features
This features will be certainly for the next version of the plugin

**Comment by ctresvaux** [comment]
hi, this feature in now available.
Thank you for your feedback
